apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  strategy: 
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nodejs
          image: devopstrainingschool/bulletin-nodejs:15
          ports:
            - containerPort: 8080 
          imagePullPolicy: Always
