apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  selector:
    app: my-app
  ports: 
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  # other  types are : NodePort & ClusterIP
